server:
  port: 18081
spring:
  application:
    name: authorization-server
  config:
    import: optional:nacos:instead
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
  datasource: # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coin-exchange
    username: root
    password: 2019dahucun
  data:
    redis:
      host: localhost
      port: 6379
      password: 2019dahucun

logging: # 日志配置
  level:
    org.springframework.security: trace
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.exchange.entity

jwt:
  access-token-validity-seconds: 10800 # accessToken有效期  3 * 60 * 60
  refresh-token-validity-seconds: 86400 # refreshToken有效期 24 * 60 * 60

# dubbo配置
#dubbo:
#  application:
#    name: dubbo-coin-authorization # 应用名称
#    qos-enable: false
#  provider:
#    token: true
#  protocol:
#    name: dubbo
#    port: -1 # Dubbo 服务端口 默认端口号是 20880  -1：则是自动分配
#  registry:
#    address: nacos://127.0.0.1:8848 # Dubbo 服务注册中心地址
#    group: DUBBO_GROUP
#  config-center:
#    address: nacos://127.0.0.1:8848 # Dubbo 配置中心地址
#    group: DUBBO_GROUP
#  metadata-report:
#    address: nacos://127.0.0.1:8848 # Dubbo 元数据中心地址
#    group: DUBBO_GROUP
