server:
  port: 18080
spring:
  application:
    name: gateway-server
  config:
    import: optional:nacos:instead
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启动态路由
          lower-case-service-id: true #
      routes:
        - id: admin-service-router
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: test_router
          uri: http://www.aliyun.com
          predicates:
            - Path=/product
    # 通过网关来完成对两种维度的限流：网关维度+api维度
    sentinel:
      transport:
        dashboard: localhost:8159 # sentinel dashboard 要把规则持久化到nacos 需要修改源码 后续在解决
      datasource:
#        ds1:
#          file:
#            file: classpath:gw-flow.json
#            rule-type: gw-flow
        ds1: #com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource 报错的话，需要添加依赖sentinel-datasource-nacos
          nacos:
            server-addr: localhost:8848
            data-id: gw_flow
            rule-type: gw_flow
#        ds2:
#          file:
#            file: classpath:api-group.json
#            rule-type: gw_api_group
        ds2:
          nacos:
            server-addr: localhost:8848
            data-id: api_group
            rule-type: gw_api_group
  data:
    redis:
      host: localhost
      port: 6379
      password: 2019dahucun

# 设置url白名单
url:
  url-white-list:
    - /admin/login
